[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

monitor_speed = 115200
monitor_filters = esp32_exception_decoder

board_build.flash_size = 4MB
board_upload.flash_size = 4MB
board_build.partitions = default.csv

; 1. Tell PlatformIO to run your python script BEFORE building
extra_scripts = pre:pre_extra_script.py

; 2. Keep only the necessary build flags, remove the hardcoded credentials
build_flags =
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1
    -O3

lib_deps =
    sparkfun/SparkFun VL53L5CX Arduino Library
    knolleary/PubSubClient @ ^2.8